### ISSUE TITLE
R packaging

### ISSUE THREAD

**Issue by caseywdunn** [shchurch/countland#1]
add tests with `testthat`, eg https://github.com/caseywdunn/hutan

**Comment by caseywdunn** [comment]
Need to figure out how to get data from shared data directory into R external data directory `inst/extdata` per https://r-pkgs.org/data.html so that it is available for vignettes

**Comment by caseywdunn** [comment]
May be able to use symbolic reference to make data appear in that directory? https://git-scm.com/docs/git-symbolic-ref

**Comment by shchurch** [comment]
tests are now in place in R version, and CRAN is live here: https://pypi.org/project/countland/
