### ISSUE TITLE
R code check

### ISSUE THREAD

**Issue by caseywdunn** [shchurch/countland#10]
Ran `devtools::check()` in countland-R. Now errors or warnings, but a couple notes:

```
❯ checking DESCRIPTION meta-information ... NOTE
  Malformed Description field: should contain one or more complete sentences.

❯ checking top-level files ... NOTE
  Non-standard files/directories found at top level:
    ‘countland.bib’ ‘manuscript.Rmd’ ‘more_vignettes_and_analyses’
    ‘nature_genetics.csl’
```

So we need to:

- Revise the description text
- Move the manuscript out of the package folder. It should go in `countland/manuscript`.

**Comment by shchurch** [comment]
The nonstandard files are taken care of,  still need to update the DESCRIPTION
